### ISSUE TITLE
Lo Scacco non Scacca.

### ISSUE THREAD

**Issue by BoostedDampi** [ThomasGhione/chess_engine#39]
**Description:**
I have been playing the chess game and noticed that when I exterminate my opponent, the game does not notify me of my victory. The game simply continues as if nothing has happened. This can be confusing and make it difficult to keep track of the overall score. It would be great if the game could display a message or pop-up indicating that the opponent has been terminated and the player has won the game.

**Steps to reproduce:**

    Start a game of chess against an opponent
    Kill the opponent
    Observe that the game does not notify the player of their victory.

**Expected behavior:**
A message or pop-up indicating that the opponent has been assassinated and the player has won the game.

**Actual behavior:**
The game does not notify the player of their murder and continues as if nothing has happened.

Thanks for your attention

**Comment by ThomasGhione** [comment]
checking the king hasn't been implemented yet :(
